In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('https://raw.githubusercontent.com/tazwar70/Databases/main/FuelConsumptionCo2.csv')
dataset = dataset.astype({'MAKE':'category','MODEL':'category','ENGINESIZE':'int64','FUELCONSUMPTION_CITY':'int64','FUELCONSUMPTION_HWY':'int64','FUELCONSUMPTION_COMB':'int64','VEHICLECLASS':'category','TRANSMISSION':'category','FUELTYPE':'category'})
dataset['MAKE'] = dataset['MAKE'].cat.codes.astype('category')
dataset['MODEL'] = dataset['MODEL'].cat.codes.astype('category')
dataset['VEHICLECLASS'] = dataset['VEHICLECLASS'].cat.codes.astype('category')
dataset['TRANSMISSION'] = dataset['TRANSMISSION'].cat.codes.astype('category')
dataset['FUELTYPE'] = dataset['FUELTYPE'].cat.codes.astype('category')
dataset.dtypes


MODELYEAR                      int64
MAKE                        category
MODEL                       category
VEHICLECLASS                category
ENGINESIZE                     int64
CYLINDERS                      int64
TRANSMISSION                category
FUELTYPE                    category
FUELCONSUMPTION_CITY           int64
FUELCONSUMPTION_HWY            int64
FUELCONSUMPTION_COMB           int64
FUELCONSUMPTION_COMB_MPG       int64
CO2EMISSIONS                   int64
dtype: object

In [3]:
X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values
print(X)
print(y)

[[  0 329   0 ...   6   8  33]
 [  0 329   0 ...   7   9  29]
 [  0 330   0 ...   5   5  48]
 ...
 [ 38 625  11 ...   9  11  24]
 [ 38 625  11 ...   9  11  25]
 [ 38 626  12 ...  10  12  22]]
[196 221 136 ... 271 260 294]


In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1,2,3,6,7])],remainder = 'passthrough')
X = ct.fit_transform(X)

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.4,random_state=1)

In [6]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [7]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_pred),1)),1))

[[272.78 274.  ]
 [203.15 200.  ]
 [202.5  196.  ]
 [160.09 161.  ]
 [315.17 320.  ]
 [221.99 224.  ]
 [185.92 192.  ]
 [188.76 189.  ]
 [222.17 221.  ]
 [176.25 182.  ]
 [236.13 230.  ]
 [287.35 283.  ]
 [191.06 189.  ]
 [385.56 400.  ]
 [188.52 186.  ]
 [161.98 168.  ]
 [193.42 196.  ]
 [325.03 338.  ]
 [269.34 271.  ]
 [223.9  225.  ]
 [419.17 413.  ]
 [222.22 223.  ]
 [250.35 248.  ]
 [270.14 264.  ]
 [308.12 308.  ]
 [232.31 232.  ]
 [138.67 147.  ]
 [261.38 246.  ]
 [179.37 179.  ]
 [269.73 274.  ]
 [241.41 246.  ]
 [405.11 409.  ]
 [234.87 235.  ]
 [309.   294.  ]
 [283.41 281.  ]
 [327.38 317.  ]
 [377.51 377.  ]
 [168.29 168.  ]
 [401.22 407.  ]
 [269.37 267.  ]
 [230.52 232.  ]
 [349.74 361.  ]
 [233.45 235.  ]
 [257.56 258.  ]
 [255.58 253.  ]
 [202.83 202.  ]
 [195.15 191.  ]
 [114.95 124.  ]
 [178.51 181.  ]
 [249.4  246.  ]
 [184.88 184.  ]
 [347.34 354.  ]
 [282.34 285.  ]
 [361.41 361.  ]
 [224.77 225.  ]
 [283.53 283.  ]
 [205.09 205.  ]
 [268.64 262.  ]
 [270.35 269. 

In [9]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9895064987671603